# Generated by Django 3.1.3 on 2020-11-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='App_users',
        ),
    ]
