# Generated by Django 3.1.3 on 2020-11-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_auto_20201103_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='app_users',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='app_users',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
